/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.User;

/**
 *
 * @author badra
 */
public class FormMenuUser extends javax.swing.JFrame {

    /**
     * Creates new form FormMenuUser
     */
    public FormMenuUser() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu5 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        MenuItemLogout = new javax.swing.JMenuItem();
        MenuItemExit = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        MenuItemPeminjaman = new javax.swing.JMenuItem();
        MenuItemPengembalian = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        MenuItemDataMobil = new javax.swing.JMenuItem();
        MenuItemDataTransaksi = new javax.swing.JMenuItem();
        MenuItemDataPelanggan = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        MenuItemInputDataPelanggan = new javax.swing.JMenuItem();

        jMenu5.setText("jMenu5");

        jMenuItem1.setText("jMenuItem1");

        jMenu8.setText("jMenu8");

        jMenu7.setText("jMenu7");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("File");

        MenuItemLogout.setText("Logout");
        MenuItemLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemLogoutActionPerformed(evt);
            }
        });
        jMenu1.add(MenuItemLogout);

        MenuItemExit.setText("Exit");
        jMenu1.add(MenuItemExit);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Transaksi");

        MenuItemPeminjaman.setText("Peminjaman");
        MenuItemPeminjaman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemPeminjamanActionPerformed(evt);
            }
        });
        jMenu2.add(MenuItemPeminjaman);

        MenuItemPengembalian.setText("Pengembalian");
        jMenu2.add(MenuItemPengembalian);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("View Data");

        MenuItemDataMobil.setText("Data Mobil");
        jMenu3.add(MenuItemDataMobil);

        MenuItemDataTransaksi.setText("Data Transaksi");
        jMenu3.add(MenuItemDataTransaksi);

        MenuItemDataPelanggan.setText("Data Pelanggan");
        jMenu3.add(MenuItemDataPelanggan);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Input Data");

        MenuItemInputDataPelanggan.setText("Input Data Pelanggan");
        MenuItemInputDataPelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemInputDataPelangganActionPerformed(evt);
            }
        });
        jMenu4.add(MenuItemInputDataPelanggan);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuItemInputDataPelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemInputDataPelangganActionPerformed
        // TODO add your handling code here:
        FormDataPelanggan panggil = new FormDataPelanggan();
        panggil.setVisible(true);
    }//GEN-LAST:event_MenuItemInputDataPelangganActionPerformed

    private void MenuItemPeminjamanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemPeminjamanActionPerformed
        // TODO add your handling code here:
        FormPeminjaman panggil = new FormPeminjaman();
        panggil.setVisible(true);
    }//GEN-LAST:event_MenuItemPeminjamanActionPerformed

    private void MenuItemLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemLogoutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuItemLogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormMenuUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormMenuUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormMenuUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormMenuUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormMenuUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MenuItemDataMobil;
    private javax.swing.JMenuItem MenuItemDataPelanggan;
    private javax.swing.JMenuItem MenuItemDataTransaksi;
    private javax.swing.JMenuItem MenuItemExit;
    private javax.swing.JMenuItem MenuItemInputDataPelanggan;
    private javax.swing.JMenuItem MenuItemLogout;
    private javax.swing.JMenuItem MenuItemPeminjaman;
    private javax.swing.JMenuItem MenuItemPengembalian;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    // End of variables declaration//GEN-END:variables
}
